In [1]:
import pandas as pd
import tensorflow as tf 
import matplotlib.pyplot as plt 
import numpy as np

2025-07-08 19:30:25.225485: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
data = pd.read_csv("../data/icml_face_data.csv")
data.head()

   emotion     Usage                                             pixels
0        0  Training  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...
1        0  Training  151 150 147 155 148 133 111 140 170 174 182 15...
2        2  Training  231 212 156 164 174 138 161 173 182 200 106 38...
3        4  Training  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...
4        6  Training  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...

In [3]:
# train_data = data[data["Usage"] == "Training"]
# test_data = data[data["Usage"] == "Testing"]

# train_data.head()

print(data.columns)

Index(['emotion', ' Usage', ' pixels'], dtype='object')

Given that the column names contain spaces at random intervals, we perform some data cleaning tasks.

In [4]:
data_columns = data.columns

for string in data_columns: 
    data = data.rename(columns = {string: string.strip()})

print(data.columns)

Index(['emotion', 'Usage', 'pixels'], dtype='object')

Now lets seperate the training and testing data. Lets first explore what Values the Usage column takes.

In [5]:
data["Usage"].value_counts()

Usage
Training       28709
PublicTest      3589
PrivateTest     3589
Name: count, dtype: int64

So we will use the Public Test and Private Test and group them together in the testing data.

In [6]:
train_data = data[data["Usage"] == "Training"]
test_data = data[data["Usage"] != "Training"]

train_data.head()

   emotion     Usage                                             pixels
0        0  Training  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...
1        0  Training  151 150 147 155 148 133 111 140 170 174 182 15...
2        2  Training  231 212 156 164 174 138 161 173 182 200 106 38...
3        4  Training  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...
4        6  Training  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...

In [7]:
test_data.head()

       emotion       Usage                                             pixels
28709        0  PublicTest  254 254 254 254 254 249 255 160 2 58 53 70 77 ...
28710        1  PublicTest  156 184 198 202 204 207 210 212 213 214 215 21...
28711        4  PublicTest  69 118 61 60 96 121 103 87 103 88 70 90 115 12...
28712        6  PublicTest  205 203 236 157 83 158 120 116 94 86 155 180 2...
28713        3  PublicTest  87 79 74 66 74 96 77 80 80 84 83 89 102 91 84 ...

Given that we've now segregated our data, there is no reason to keep the usage column and so we simply drop it.

In [8]:
train_data.drop(columns=["Usage"], inplace = True)
train_data.head()

/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2056591952.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data.drop(columns=["Usage"], inplace = True)

   emotion                                             pixels
0        0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...
1        0  151 150 147 155 148 133 111 140 170 174 182 15...
2        2  231 212 156 164 174 138 161 173 182 200 106 38...
3        4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...
4        6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...

In [9]:
test_data.drop(columns=["Usage"], inplace = True)
test_data.head()

/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/3513069122.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data.drop(columns=["Usage"], inplace = True)

       emotion                                             pixels
28709        0  254 254 254 254 254 249 255 160 2 58 53 70 77 ...
28710        1  156 184 198 202 204 207 210 212 213 214 215 21...
28711        4  69 118 61 60 96 121 103 87 103 88 70 90 115 12...
28712        6  205 203 236 157 83 158 120 116 94 86 155 180 2...
28713        3  87 79 74 66 74 96 77 80 80 84 83 89 102 91 84 ...

Let us now analyse the type of data present in our Dataset to identify the most optimal classification algorithm and model training strategy.

In [10]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28709 entries, 0 to 28708
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   emotion  28709 non-null  int64
 1   pixels   28709 non-null  object
dtypes: int64(1), object(1)
memory usage: 672.9+ KB

There are no null values in our dataset, and hence we don't need to drop any rows.

In [11]:
pixels_array = np.array(train_data["pixels"])
pixels_array

array(['70 80 82 72 58 58 60 63 54 58 60 48 89 115 121 119 115 110 98 91 84 84 90 99 110 126 143 153 158 171 169 172 169 165 129 110 113 107 95 79 66 62 56 57 61 52 43 41 65 61 58 57 56 69 75 70 65 56 54 105 146 154 151 151 155 155 150 147 147 148 152 158 164 172 177 182 186 189 188 190 188 180 167 116 95 103 97 77 72 62 55 58 54 56 52 44 50 43 54 64 63 71 68 64 52 66 119 156 161 164 163 164 167 168 170 174 175 176 178 179 183 187 190 195 197 198 197 198 195 191 190 145 86 100 90 65 57 60 54 51 41 49 56 47 38 44 63 55 46 52 54 55 83 138 157 158 165 168 172 171 173 176 179 179 180 182 185 187 189 189 192 197 200 199 196 198 200 198 197 177 91 87 96 58 58 59 51 42 37 41 47 45 37 35 36 30 41 47 59 94 141 159 161 161 164 170 171 172 176 178 179 182 183 183 187 189 192 192 194 195 200 200 199 199 200 201 197 193 111 71 108 69 55 61 51 42 43 56 54 44 24 29 31 45 61 72 100 136 150 159 163 162 163 170 172 171 174 177 177 180 187 186 187 189 192 192 194 195 196 197 199 200 201 200 197 201 137 58 98 92 57 62 53 47 41 40 51 43 24 35 52 63 75 104 129 143 149 158 162 164 166 171 173 172 174 178 178 179 187 188 188 191 193 194 195 198 199 199 197 198 197 197 197 201 164 52 78 87 69 58 56 50 54 39 44 42 26 31 49 65 91 119 134 145 147 152 159 163 167 171 170 169 174 178 178 179 187 187 185 187 190 188 187 191 197 201 199 199 200 197 196 197 182 58 62 77 61 60 55 49 59 52 54 44 22 30 47 68 102 123 136 144 148 150 153 157 167 172 173 170 171 177 179 178 186 190 186 189 196 193 191 194 190 190 192 197 201 203 199 194 189 69 48 74 56 60 57 50 59 59 51 41 20 34 47 79 111 132 139 143 145 147 150 151 160 169 172 171 167 171 177 177 174 180 182 181 192 196 189 192 198 195 194 196 198 201 202 195 189 70 39 69 61 61 61 53 59 59 45 40 26 40 61 93 124 135 138 142 144 146 151 152 158 165 168 168 165 161 164 173 172 167 172 167 180 198 198 193 199 195 194 198 200 198 197 195 190 65 35 68 59 59 62 57 60 59 50 44 32 54 90 115 132 137 138 140 144 146 146 156 165 168 174 176 176 175 168 168 169 171 175 171 172 192 194 184 198 205 201 194 195 193 195 192 186 57 38 72 65 57 62 58 57 60 54 49 47 79 116 130 138 141 141 139 141 143 145 157 164 164 166 173 174 176 179 179 176 181 189 188 173 180 175 160 182 189 198 192 189 190 190 188 172 46 44 64 66 59 62 57 56 62 53 50 66 103 133 137 141 143 141 136 132 131 136 127 118 111 107 108 123 131 143 154 158 166 177 181 175 170 159 148 171 161 176 185 192 194 188 190 162 53 49 58 63 61 61 55 56 61 51 50 81 116 139 142 142 146 144 136 128 119 112 97 85 90 91 88 92 90 80 81 84 106 122 132 144 145 144 147 163 147 163 173 181 190 187 191 167 61 48 53 61 61 58 54 56 61 51 53 89 123 140 144 145 146 147 136 122 107 99 95 92 90 87 83 76 67 52 46 52 63 69 83 96 119 132 148 159 136 137 143 138 143 152 156 156 70 48 50 59 61 57 54 54 61 52 56 93 124 135 140 144 148 150 140 125 114 101 80 54 56 54 41 41 33 40 39 35 49 60 63 74 107 129 147 147 116 111 100 77 76 86 108 111 73 49 50 60 62 60 57 55 63 59 56 89 121 134 139 146 151 152 150 141 127 111 96 77 85 70 32 31 37 91 65 50 48 59 73 83 112 136 155 130 60 46 38 40 43 81 116 91 72 52 48 58 62 62 59 53 61 59 52 85 114 134 140 147 154 159 158 153 145 143 150 126 121 125 68 45 89 137 95 70 78 75 95 109 131 153 171 94 23 16 32 82 82 65 113 77 71 54 48 56 62 62 60 53 60 56 52 75 108 133 141 149 158 166 169 167 163 156 155 146 112 119 134 127 142 140 121 117 129 114 120 129 146 174 191 98 46 33 33 109 147 98 109 67 73 55 50 56 64 64 61 58 61 53 54 64 106 129 140 148 159 169 175 176 174 165 159 156 145 120 115 124 127 131 133 141 147 142 141 147 161 182 202 154 114 96 100 158 158 153 123 61 76 57 48 56 64 64 63 62 61 54 55 44 97 131 137 147 158 168 177 181 183 179 170 168 169 165 155 152 151 152 154 162 165 158 153 158 168 187 206 186 147 135 144 145 152 178 115 57 74 58 48 58 64 63 63 59 63 55 53 66 104 130 132 144 153 162 170 180 185 187 181 178 182 180 177 173 171 171 177 176 172 164 161 167 164 185 207 197 173 152 141 141 161 191 104 54 69 60 48 57 65 62 60 57 64 55 50 94 111 124 130 135 150 159 163 172 179 184 184 178 178 177 173 171 174 177 178 176 169 165 161 163 161 180 205 201 183 171 177 178 180 194 101 55 65 60 47 55 65 63 59 58 63 57 52 90 105 117 122 130 143 153 157 163 171 174 182 183 182 178 174 175 175 177 175 172 163 161 159 157 162 178 200 201 188 181 172 177 187 198 98 57 63 61 48 52 61 64 63 60 65 57 51 95 104 113 117 127 136 145 152 156 162 162 165 173 177 182 183 183 180 181 177 165 153 154 152 153 160 174 193 200 188 185 180 182 192 196 101 60 60 56 49 50 60 66 64 62 64 59 53 99 104 111 112 118 132 142 147 155 158 160 159 162 171 176 184 186 183 180 169 154 141 135 145 155 164 180 196 205 188 189 188 189 193 192 98 61 64 55 49 49 60 66 63 64 63 60 57 99 105 108 112 113 125 139 143 150 155 158 164 169 174 176 182 183 182 177 163 141 133 147 151 164 170 185 200 210 194 188 192 186 185 180 88 64 67 60 46 50 59 65 64 64 64 59 56 101 103 108 109 109 118 134 143 143 147 155 159 166 171 174 177 179 178 172 153 129 143 161 159 166 171 186 197 207 203 185 191 183 179 164 73 67 67 66 48 50 57 65 65 63 64 61 57 103 108 114 112 110 115 128 138 144 145 152 156 159 164 168 172 172 169 161 139 125 147 156 161 162 164 180 188 188 197 185 187 181 180 137 65 70 68 70 52 47 53 62 65 63 65 61 58 105 109 112 120 113 112 122 134 141 149 150 153 155 159 164 167 167 162 152 134 115 126 119 106 99 109 141 158 150 155 175 184 176 175 106 63 70 68 68 50 46 50 57 63 63 64 61 59 107 110 110 117 117 114 117 128 137 147 148 150 153 156 161 162 163 156 150 148 105 70 45 26 25 47 73 74 79 128 177 180 173 157 77 66 68 67 68 52 49 51 56 62 62 62 62 60 101 107 108 114 115 114 117 125 134 143 148 149 152 154 158 160 158 155 160 158 132 88 73 73 64 52 66 91 138 160 174 173 171 125 64 67 63 64 68 54 50 49 54 60 60 60 62 60 98 105 105 109 111 114 117 125 131 139 145 148 153 153 156 157 156 161 168 165 153 139 122 115 105 89 103 150 182 161 171 173 162 89 64 64 62 64 69 56 48 49 56 58 60 59 62 60 89 99 108 106 109 111 119 120 125 134 140 146 152 153 153 153 156 159 162 160 150 136 129 133 133 122 133 148 178 168 168 175 132 61 67 66 65 63 69 57 47 50 55 58 59 61 62 60 89 96 105 107 105 107 117 120 123 124 133 141 149 153 151 145 151 145 139 140 138 128 126 124 129 125 136 142 164 172 168 168 87 58 67 63 62 61 69 57 39 44 55 56 59 63 62 62 84 91 92 98 102 103 113 119 121 118 128 138 146 151 147 142 140 128 127 128 129 126 135 140 135 130 143 146 149 166 174 131 62 65 62 59 67 63 68 83 89 65 42 52 60 60 62 63 77 84 84 91 99 101 107 112 117 118 122 134 145 149 144 134 127 127 129 130 134 125 126 132 152 153 151 150 151 165 171 87 59 65 64 61 58 86 122 138 208 207 154 71 52 56 55 56 69 77 83 85 93 91 102 112 116 118 119 127 140 144 142 131 112 95 85 75 62 58 56 59 87 88 83 127 142 165 149 62 65 62 59 77 113 192 156 84 185 196 197 168 81 70 75 69 58 65 73 82 81 79 95 107 114 116 116 123 136 142 136 132 131 102 71 58 49 41 33 41 36 49 60 99 136 168 111 53 63 71 138 186 203 195 146 87 91 72 79 95 103 82 61 74 55 57 68 75 76 77 84 96 106 110 111 121 130 138 136 142 153 159 152 152 154 145 133 136 147 158 156 155 147 158 74 57 60 123 181 174 126 89 72 67 57 43 55 67 76 86 60 45 51 45 52 68 75 73 77 88 96 100 104 113 115 121 134 146 149 146 149 148 155 168 174 179 178 169 169 174 161 131 44 47 82 150 168 136 104 75 66 80 67 58 48 54 68 88 121 102 51 45 38 53 66 65 70 86 92 96 102 103 109 116 130 136 136 133 136 138 137 135 128 130 143 158 165 164 147 87 62 74 123 160 170 100 99 107 79 71 86 75 57 45 49 65 122 130 43 48 40 39 55 61 59 71 82 87 88 93 105 118 123 128 130 124 111 98 94 88 67 55 84 129 147 148 105 48 82 142 161 164 164 76 72 85 100 88 72 90 84 54 48 54 73 100 73 36 44 31 37 53 51 55 67 74 77 87 97 108 118 125 132 122 106 86 80 82 75 73 83 110 129 126 46 22 130 177 196 193 166 72 52 54 73 100 92 75 99 95 65 68 61 63 91 65 42 37 22 28 39 44 57 68 74 83 92 101 119 131 143 141 134 136 140 139 134 136 139 138 136 85 23 114 202 198 199 180 173 98 36 86 130 150 137 99 77 101 99 72 56 43 77 82 79 70 56 28 20 25 36 50 63 73 83 98 111 124 139 156 160 159 169 168 165 163 159 149 114 43 26 133 183 192 177 152 137 130 125 139 173 195 186 137 101 88 101 105 70 46 77 72 84 87 87 81 64 37 20 31 40 46 65 88 108 110 125 149 157 153 162 164 158 159 154 140 78 21 11 61 144 168 173 157 138 150 148 132 159 182 183 136 106 116 95 106 109 82',
       '151 150 147 155 148 133 111 140 170 174 182 154 153 164 173 178 185 185 189 187 186 193 194 185 183 186 180 173 166 161 147 133 172 151 114 161 161 146 131 104 95 132 163 123 119 129 140 120 151 149 149 153 137 115 129 166 170 181 164 143 157 156 169 179 185 183 186 186 184 190 191 184 186 190 183 175 168 160 147 136 135 167 136 108 153 167 149 137 111 90 134 162 121 122 141 137 151 151 156 143 116 124 159 164 174 169 135 144 155 153 164 170 176 178 177 178 187 185 181 182 183 181 178 170 164 158 148 144 130 136 173 130 97 137 167 157 138 113 90 138 168 109 123 146 151 152 155 127 113 159 167 170 171 142 131 140 154 162 168 169 169 164 168 173 176 179 178 176 173 172 170 161 154 152 146 145 137 124 130 171 124 102 133 164 152 138 110 86 154 149 100 139 153 151 136 113 142 159 161 174 150 127 136 140 154 164 163 167 173 172 171 170 167 168 172 167 162 161 160 163 163 154 145 146 140 133 122 135 167 127 101 126 164 147 132 95 91 166 115 113 158 143 121 134 153 153 164 162 131 130 136 146 155 158 155 157 163 163 158 159 159 161 165 156 153 156 159 163 163 150 149 150 146 140 137 122 147 154 116 97 133 164 142 123 77 117 147 95 149 127 129 153 142 165 171 136 116 129 130 139 140 149 153 147 146 150 150 155 151 155 156 153 152 157 165 165 160 150 156 156 148 141 135 135 132 147 141 110 97 143 165 142 101 66 151 117 136 125 148 139 153 173 159 118 116 119 123 131 134 145 145 137 142 151 157 159 153 154 153 150 159 170 171 167 160 160 159 158 152 141 145 144 140 119 144 133 106 101 151 148 130 70 119 148 129 143 146 134 165 165 134 121 123 121 125 129 136 150 159 163 165 161 157 155 147 150 148 135 156 171 169 171 166 165 165 158 153 146 147 150 137 122 112 144 122 94 111 158 143 91 74 155 134 147 131 154 167 153 107 125 129 134 137 134 136 154 168 174 171 168 163 156 151 150 146 146 166 171 173 176 177 191 187 175 180 179 174 165 142 134 108 111 137 108 86 143 156 116 64 133 143 129 138 162 167 132 117 127 128 140 147 145 155 159 165 170 172 166 160 154 156 160 156 156 158 153 170 188 198 208 203 209 219 217 200 174 171 147 128 92 129 131 88 103 159 135 75 111 133 126 160 156 159 117 132 129 131 144 160 165 162 166 170 165 160 160 159 153 149 150 151 148 120 132 189 183 180 177 187 201 194 186 181 170 167 146 118 117 100 139 112 74 139 145 85 91 120 151 156 164 129 111 135 140 139 142 158 163 172 190 195 189 168 156 149 143 137 140 140 132 114 142 150 129 133 125 138 140 132 114 124 131 118 143 125 126 82 97 141 72 113 152 93 77 134 157 149 166 95 124 136 142 156 165 179 189 198 198 186 186 188 157 126 124 118 129 128 115 95 100 90 84 81 66 72 80 77 63 59 65 70 67 86 105 82 95 138 89 94 153 106 74 153 148 165 134 80 134 137 149 173 187 193 201 185 169 141 128 150 139 113 119 123 128 114 91 71 60 51 69 78 80 80 79 76 76 65 65 85 103 46 73 142 85 114 114 75 145 121 70 150 141 168 76 91 130 144 179 197 210 190 164 146 128 121 90 92 90 90 114 104 109 110 81 52 53 87 96 94 99 96 88 95 108 116 110 97 120 98 64 120 77 105 130 67 131 128 67 137 150 136 46 106 126 164 164 151 150 131 115 103 88 90 91 92 78 56 49 65 90 115 66 29 91 99 104 107 88 94 105 111 118 113 116 103 103 120 47 83 110 120 134 67 116 136 74 133 163 82 51 113 115 104 112 144 162 138 104 96 93 95 90 91 99 103 55 29 46 45 16 40 104 95 101 92 93 96 80 69 82 99 98 108 116 128 70 102 117 127 140 79 105 139 82 140 149 23 43 103 50 78 179 185 147 111 113 117 106 91 95 100 91 96 92 19 6 19 8 35 88 64 66 60 72 68 34 35 70 85 101 118 130 143 82 114 125 130 149 93 104 139 83 148 130 67 86 94 42 142 173 151 128 124 106 96 103 90 89 100 97 95 103 28 48 127 126 38 87 81 68 64 70 74 51 68 92 112 139 149 152 158 100 134 128 133 159 105 95 139 86 153 113 62 126 130 62 135 136 127 122 93 67 54 44 42 43 60 76 86 104 41 115 197 211 112 67 118 109 107 93 84 83 101 108 129 150 158 156 143 105 140 129 131 166 115 85 137 87 156 99 21 89 104 46 117 135 113 78 52 89 94 46 24 45 54 65 95 92 49 161 213 212 188 85 97 133 130 124 121 122 136 147 143 154 151 173 124 115 147 129 124 164 136 95 126 85 159 94 36 97 117 78 93 130 90 73 77 94 86 61 60 72 69 91 113 80 76 188 214 213 200 143 66 119 138 150 151 151 159 163 156 154 162 140 107 136 148 135 115 158 150 116 111 87 161 101 50 109 111 98 69 99 97 109 111 114 106 95 96 99 101 109 122 70 111 193 214 217 200 183 115 78 124 157 167 170 172 166 161 147 127 118 134 138 141 141 119 147 155 131 98 96 163 103 72 120 112 115 80 100 117 100 105 127 138 133 132 140 137 121 103 64 153 200 215 218 205 183 169 127 77 92 111 122 126 128 128 129 135 145 141 138 133 138 127 139 169 127 83 93 161 106 87 122 106 117 114 88 124 116 108 135 150 151 156 163 162 121 66 110 177 201 212 214 200 181 162 155 117 97 103 109 115 119 131 141 147 149 141 146 140 128 130 140 170 101 87 89 163 109 105 123 103 112 133 113 95 132 139 160 167 169 158 149 118 72 89 133 169 189 197 204 194 180 172 166 138 114 112 114 120 119 125 134 140 150 145 142 145 142 144 152 164 116 95 84 159 113 111 124 101 112 136 134 115 107 118 131 138 129 108 93 75 88 112 136 170 183 181 178 181 177 177 180 175 130 110 119 125 130 131 135 138 142 146 136 130 146 142 157 169 135 91 100 150 115 114 138 107 114 133 125 124 133 137 128 119 106 102 98 93 96 141 160 147 149 150 145 153 161 147 146 175 162 114 112 121 127 128 131 129 134 142 136 124 139 141 157 175 138 106 149 145 119 119 150 109 115 136 129 126 131 137 130 114 106 108 109 99 115 156 138 116 134 139 130 140 119 53 45 103 139 131 101 98 117 126 130 123 124 133 137 131 130 143 160 177 148 158 182 146 122 117 161 118 116 131 134 130 130 124 121 118 117 119 112 92 107 134 74 29 73 122 129 126 78 33 42 65 107 123 103 97 96 113 121 119 121 124 131 130 128 157 176 179 185 187 181 158 124 111 169 131 116 123 129 130 129 129 128 125 124 114 86 89 104 91 46 31 35 74 113 107 93 79 79 94 121 131 126 119 92 100 114 114 117 115 120 125 130 164 179 188 192 182 184 182 140 106 170 147 120 121 129 130 127 128 129 128 123 98 62 98 116 113 94 90 85 81 80 104 116 126 141 136 148 148 129 122 101 95 107 107 117 123 125 130 139 165 179 184 192 184 183 191 167 119 173 158 136 118 130 131 125 123 123 125 114 81 71 131 147 148 138 133 117 101 88 118 131 143 163 167 165 164 146 132 122 107 95 104 115 126 136 137 146 168 180 179 195 187 183 188 186 141 158 165 147 116 131 130 124 118 117 119 102 70 101 140 154 153 142 134 125 118 117 118 116 120 137 149 163 172 158 144 137 138 117 112 123 129 139 146 157 167 175 178 196 190 184 190 188 167 155 174 161 134 119 114 121 118 113 109 89 93 134 140 161 170 145 126 108 121 117 108 117 136 146 142 138 150 149 147 135 142 122 115 142 149 144 144 162 168 171 176 192 187 182 192 183 185 175 174 145 87 65 63 84 112 114 98 92 109 140 155 151 147 123 103 111 112 116 108 111 127 130 117 115 124 129 138 124 118 120 114 135 144 141 144 154 168 170 174 187 182 179 187 184 184 187 132 28 6 24 36 39 69 111 99 84 109 134 133 108 97 84 75 78 74 81 80 62 48 32 27 36 42 56 88 87 86 123 130 138 138 134 141 151 170 167 173 189 184 181 187 186 191 192 63 26 18 3 16 22 23 85 106 98 110 112 89 47 35 41 20 18 21 13 9 7 3 2 4 4 3 4 30 40 49 112 129 142 143 139 144 151 171 174 177 188 186 181 189 189 170 124 47 33 28 8 4 12 11 48 111 113 100 85 50 19 4 5 3 10 14 12 15 26 31 35 38 37 40 62 84 73 61 124 143 138 130 140 139 152 157 170 179 186 186 181 179 115 39 26 14 6 10 3 1 5 2 48 124 117 106 71 34 42 32 17 17 24 35 41 49 63 67 70 72 88 106 118 107 97 75 95 139 138 125 130 131 150 160 173 183 188 186 184 114 54 84 157 71 0 6 5 4 3 0 75 122 109 103 69 53 67 68 59 55 54 59 65 74 88 97 104 109 119 129 128 127 130 98 96 136 156 130 117 128 148 165 176 190 191 186 183 74 64 167 201 164 43 1 0 0 3 46 114 118 110 110 67 66 97 83 86 87 98 93 98 102 112 119 119 125 126 130 128 127 135 134 112 123 150 136 118 126 146 158 179 196 188 185 185 142 50 136 182 194 173 83 58 60 100 130 121 113 120 116 80 77 95 103 111 116 124 116 120 117 119 108 123 129 144 160 143 129 130 127 132 123 149 132 117 125 142 151 188 194 187 184 185 197 128 84 169 177 199 178 162 147 154 146 124 107 129 120 96 88 99 131 131 145 131 137 148 131 133 128 124 118 142 167 159 130 136 134 127 128 143 133 118 139 140 144 192 196 187 184 184 188 188 121 86 175 189 192 157 148 144 149 126 113 123 127 106 96 107 145 143 144 131 147 150 143 147 134 126 131 151 170 162 148 116 139 122 124 141 127 112 128 116 113 159 201 185 185 186 188 187 196 129 85 171 194 171 142 144 144 128 119 116 121 116 100 108 136 146 128 135 151 146 152 150 158 143 133 143 159 153 152 128 137 133 125 127 102 108 109 105 102 106 197 186 182 187 186 184 185 197 124 84 174 185 150 129 143 135 115 102 111 124 112 109 132 146 135 149 148 143 163 156 159 150 139 128 116 125 133 109 130 147 130 121 105 108 95 108 102 67 171 193 183 184',

Let us know convert the training and testing dataframe, so that each column represents a specific pixel.

In [12]:
new_cols = train_data["pixels"].str.split(" ", expand=True)


emotion_col = train_data["emotion"]
train_data.drop(columns=["pixels", "emotion"],inplace = True)
train_data[list(np.arange(0,2304))] = new_cols
train_data["emotion"] = emotion_col

train_data.head()

/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data.drop(columns=["pixels", "emotion"],inplace = True)
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1120655571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[list(np.arange(0,2304))] = new_cols

,0,1,2,3,4,5,6,7,8,9,...,2295,2296,2297,2298,2299,2300,2301,2302,2303,emotion
0,70,80,82,72,58,58,60,63,54,58,...,182,183,136,106,116,95,106,109,82,0
1,151,150,147,155,148,133,111,140,170,174,...,108,95,108,102,67,171,193,183,184,0
2,231,212,156,164,174,138,161,173,182,200,...,138,152,122,114,101,97,88,110,152,2
3,24,32,36,30,32,23,19,20,30,41,...,126,132,132,133,136,139,142,143,142,4
4,4,0,0,0,0,0,0,0,0,0,...,34,31,31,31,27,31,30,29,30,6

In [13]:
new_cols = test_data["pixels"].str.split(" ", expand=True)


emotion_col = test_data["emotion"]
test_data.drop(columns=["pixels", "emotion"],inplace = True)
test_data[list(np.arange(0,2304))] = new_cols
test_data["emotion"] = emotion_col

test_data.head()

/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data.drop(columns=["pixels", "emotion"],inplace = True)
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols
/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/2455931371.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[list(np.arange(0,2304))] = new_cols

,0,1,2,3,4,5,6,7,8,9,...,2295,2296,2297,2298,2299,2300,2301,2302,2303,emotion
28709,254,254,254,254,254,249,255,160,2,58,...,92,99,84,22,0,0,42,129,180,0
28710,156,184,198,202,204,207,210,212,213,214,...,199,197,193,188,184,180,172,167,161,1
28711,69,118,61,60,96,121,103,87,103,88,...,93,92,90,92,93,92,88,87,90,4
28712,205,203,236,157,83,158,120,116,94,86,...,211,213,206,196,181,112,43,82,86,6
28713,87,79,74,66,74,96,77,80,80,84,...,32,33,35,38,40,45,41,34,32,3

In [14]:
train_data.columns

Index([        0,         1,         2,         3,         4,         5,
               6,         7,         8,         9,
       ...
            2295,      2296,      2297,      2298,      2299,      2300,
            2301,      2302,      2303, 'emotion'],
      dtype='object', length=2305)

In [15]:
test_data.columns

Index([        0,         1,         2,         3,         4,         5,
               6,         7,         8,         9,
       ...
            2295,      2296,      2297,      2298,      2299,      2300,
            2301,      2302,      2303, 'emotion'],
      dtype='object', length=2305)

In [16]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28709 entries, 0 to 28708
Columns: 2305 entries, 0 to emotion
dtypes: int64(1), object(2304)
memory usage: 505.1+ MB

We can see from above that only the emotion column has numeric values. So we convert all the columns into int values using the code below.

In [17]:
columns = train_data.columns

for col in columns: 
    train_data[col] = pd.to_numeric(train_data[col])

train_data.info()

/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/3678682699.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[col] = pd.to_numeric(train_data[col])

<class 'pandas.core.frame.DataFrame'>
Index: 28709 entries, 0 to 28708
Columns: 2305 entries, 0 to emotion
dtypes: int64(2305)
memory usage: 505.1 MB

Similarly for the test data we have .

In [18]:
columns2 = test_data.columns

for col in columns2: 
    test_data[col] = pd.to_numeric(test_data[col])

test_data.info()

/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1926734213.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[col] = pd.to_numeric(test_data[col])

<class 'pandas.core.frame.DataFrame'>
Index: 7178 entries, 28709 to 35886
Columns: 2305 entries, 0 to emotion
dtypes: int64(2305)
memory usage: 126.3 MB

Now, we don't really want to have all emotions in our emotion column. For our purposes, we want to work with three major emotional states, namely focusses, distracted and stressed. To be able to do this, let us analyse the emotion column of our data in more detail.

In [19]:
train_data["emotion"].value_counts()

emotion
3    7215
6    4965
4    4830
2    4097
0    3995
5    3171
1     436
Name: count, dtype: int64

From the Dataset description, we note the following categorisation: 
0=Angry, 
1=Disgust, 
2=Fear, 
3=Happy, 
4=Sad, 
5=Surprise, 
6=Neutral.

We categorise sad, fear, and angry as Stressed (which we label 0), we categorise Disgust, Happy and Surprise as Distracted (which we label 1), and finally we categorise Neutral as Focussed (which we label 2).

In [20]:
emotion = list(train_data["emotion"])

for i in range(len(emotion)): 
    if emotion[i] in [0, 2, 4]: 
        emotion[i] = 0
    elif emotion[i] in [1, 3, 5]:
        emotion[i] = 1
    else: 
        emotion[i] = 2
    
train_data["emotion"] = pd.Series(emotion)

train_data["emotion"].value_counts()

/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/1871607368.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data["emotion"] = pd.Series(emotion)

emotion
0    12922
1    10822
2     4965
Name: count, dtype: int64

In [21]:
train_data["emotion"].value_counts()*100/len(train_data["emotion"])

emotion
0    45.010276
1    37.695496
2    17.294228
Name: count, dtype: float64

In [22]:
test_data["emotion"].value_counts()

emotion
3    1774
4    1247
6    1233
2    1024
0     958
5     831
1     111
Name: count, dtype: int64

In [23]:
emotion2 = list(test_data["emotion"])
for i in range(len(emotion2)): 
    if emotion2[i] in [0, 2, 4]: 
        emotion2[i] = 0
    elif emotion2[i] in [1, 3, 5]:
        emotion2[i] = 1
    elif emotion2[i] == 6: 
        emotion2[i] = 2
    
emotion2 = pd.Series(emotion2)

In [24]:
test_data.reset_index(drop = True, inplace = True)

In [25]:
test_data["emotion"].reset_index(drop = True, inplace = True)

In [26]:
test_data["emotion"]

0       0
1       1
2       4
3       6
4       3
       ..
7173    6
7174    3
7175    0
7176    3
7177    2
Name: emotion, Length: 7178, dtype: int64

In [27]:
test_data["emotion"] = emotion2
test_data["emotion"]

/var/folders/9k/th5b0bj95938tdg9_4l923tc0000gn/T/ipykernel_6495/3075852942.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data["emotion"] = emotion2

0       0
1       1
2       0
3       2
4       1
       ..
7173    2
7174    1
7175    0
7176    1
7177    0
Name: emotion, Length: 7178, dtype: int64

In [28]:
test_data["emotion"].value_counts()

emotion
0    3229
1    2716
2    1233
Name: count, dtype: int64

We do notice that our data is slightly imbalanced as there are many more instances of stressed and distracted than those of focussed. Let use nevertheless train the data with the SVM model nd then determine if we should oversample the data.

Now we see that all the columns in both our training and testing dataset have purely integer values. Hence, now we will set aside the testing data and only work on the training data to prevent our models from having any sort of bias.

This means we will now first analyse the data and then train our SVM classification model.

In [30]:
train_data.to_csv("/Users/almarai/Private Projects/CogniScan/CogniScan/data/processed/train_data_processed.csv", index = False)
test_data.to_csv("/Users/almarai/Private Projects/CogniScan/CogniScan/data/processed/test_data_processed.csv", index = False)